### ISSUE TITLE
About path definition

### ISSUE THREAD

**Issue by mill6-plat6aux** [wbcsd/pact-openapi#1]
Hello everyone,

In Tech Spec, the path for `ListFootprints` is expressed as `Subpath/2/footprints`.

In other words, the `Subpath` part can be expressed freely according to the convenience of the application, but `/2/footprints` must be included in the path, right?

In OpenAPI Spec, the path for `ListFootprints` is expressed as `/footprints`. I feel that this does not fully express the above rules.
(`https://example.com/footprints` would be allowed.)

Please tell me the intention behind defining it this way.

**Comment by schuur** [comment]
My initial thinking was removing the version from the individual paths and specify it in the `servers` section. However, this way an implementor would not be absolutely required to use the `/2/` in their paths. With earlier 2.x versions already published, this is indeed not something we can do for version 2.3.
Thanks for noticing, I will change these paths to `/2/operation' again.
